### PR TITLE
Hotfix/body encoding

### LINKED ISSUE #169: Body forwarded from Octoparts gets mangled when sending non-Latin-1 chars
How to reproduce:

1. Make an AggregateRequest that contains one or more PartRequests with UTF-8 body characters
2. Send the AggregateRequest
3. Observe that the characters inside the body are mangled on the receiving end (after being forwarded from Octoparts)

### PR DESCRIPTION
**Pull request by lloydmeta**
Closes #169 

Changes:

- Encode the body as UTF-8 before sending Http requests to dependent systems
- Add a test to enforce this.

### CODE REVIEW

File: test/com/m3/octoparts/http/BlockingHttpRetrieveSpec.scala [hunk 1]
```diff
@@ -63,6 +64,24 @@ class BlockingHttpRetrieveSpec extends FunSpec with Matchers with ScalaFutures {
...
+        it("should have UTF-8 entity encoding") {
+          Seq(Post, Put, Patch).foreach { method =>
+            new HttpRetrieveBodyContext {
+              override def httpMethod: HttpMethod = method
+              command.request match {
+                case req: HttpEntityEnclosingRequest => {
+                  val entity = req.getEntity
+                  entity.getContentType.getValue should include("charset=UTF-8")
+                }
+                case _ => fail("The request doesn'T contain entities")
```
Comment (mauhiz) [inline test/com/m3/octoparts/http/BlockingHttpRetrieveSpec.scala]: minor typo

**Comment by mauhiz** [comment]
LGTM. waiting for build

File: test/com/m3/octoparts/http/BlockingHttpRetrieveSpec.scala (hunk 1 above)
Comment (lloydmeta) [inline test/com/m3/octoparts/http/BlockingHttpRetrieveSpec.scala]: Ah nice catch; fixed.
